version: "3.9"
services:
  server:
    build:
      context: ./server
    container_name: wedding_server
    ports:
      - "8000:8000"
    volumes:
      - server_uploads:/app/uploads
    environment:
      - UVICORN_WORKERS=1
    restart: unless-stopped

  client:
    build:
      context: ./client
      args:
        # Adjust if server runs elsewhere in prod
        VITE_API_BASE_URL: http://localhost:8000
    container_name: wedding_client
    ports:
      - "5173:80"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  server_uploads: 